# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for more details

app = "household-app" # Your app name
primary_region = "fra" # Change to your preferred region (e.g., "iad" for Virginia, "lhr" for London)

[build]
  dockerfile = "Dockerfile"
  target = "runner"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  strategy = "bluegreen"
  release_command = "pnpm --filter backend exec prisma migrate deploy"

[mounts]
  source = "pg_data"
  destination = "/data"
  initial_size = "10"
  auto_extend_size = "10"
  auto_extend_threshold = "80"
  auto_extend_step = "5"
