# fly.toml app configuration file for your backend
# See https://fly.io/docs/reference/configuration/ for more details

app = "household-app"  # Replace with your Fly.io app name
primary_region = "waw"  # Choose your preferred region (e.g., waw, fra, ord, etc.)

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["heroku/nodejs"]
  build_command = "pnpm install && pnpm prisma generate && pnpm run build"

[deploy]
  strategy = "immediate"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
